[global.config]
  as = 65003
  router-id = "10.10.0.3"

[zebra]
  [zebra.config]
    enabled = true
    url = "unix:/var/run/quagga/zserv.api"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.10.0.1"
    peer-as = 65001

[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.10.0.2"
    peer-as = 65002
