[global.config]
  as = 65001
  router-id = "10.10.0.1"

[zebra]
  [zebra.config]
    enabled = true
    url = "unix:/var/run/quagga/zserv.api"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.10.0.10"
    peer-as = 65000
